{
 "title": "Neo4j Queries",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(neo4j_db_status, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count ((neo4j_db_query{namespace=\"$namespace\"})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Queries AVG per DB",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (neo4j_db_query{namespace=\"$namespace\"}) by (database)",
     "legendFormat": "{{datbase}}"
    }
   ]
  },
  {
   "title": "Queries Page Hits AVG per DB",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (neo4j_db_query_page_hits{namespace=\"$namespace\"}) by (database)",
     "legendFormat": "{{datbase}}"
    }
   ]
  },
  {
   "title": "Queries AVG per Node",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (neo4j_db_query{namespace=\"$namespace\"}) by (address)",
     "legendFormat": "{{datbase}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum (neo4j_db_query{namespace=\"$namespace\"}) by (address,currentQueryId,database,pageHits,status,transactionId)"
    }
   ]
  },
  { "title": "Databases Statuses ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Quarantined databases",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count (neo4j_db_status{namespace=\"$namespace\",currentStatus!=\"online\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Databases Statuses ",
   "type": "table",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 17 },
   "targets": [
    {
     "expr": "group (neo4j_db_status{namespace=\"$namespace\"}) by (currentStatus,name,address,namespace)"
    }
   ]
  }
 ]
}